const pet = require('./petBuilder')

const pet1 = new pet()
    .setName('Mpuss')
    .setType('cat')
    .setGender('male')
    .build()
const pet2 = new pet()
    .setName('gukk')
    .setType('dog')
    .setGender('female')
    .build()
const pet3 = new pet()
    .setType('cat')
    .setGender('male')
    .build()

console.log(pet1)
console.log(pet2)
console.log(pet3)